[graph]
# If true, metadata will be collected with `--all-features`.
all-features = true

[licenses]
version = 2

# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Zlib",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "MPL-2.0",
    "BSL-1.0",
    "CC0-1.0",
    "OFL-1.1",
    "LicenseRef-UFL-1.0",
    "OpenSSL"
]

# Some crates don't have (easily) machine readable licensing information,
# adding a clarification entry for it allows you to manually specify the
# licensing information.

# Some parts of NihAV were kindly relicenced for us under MIT by the author.
# See: https://codecs.multimedia.cx/nihav-relicensed-code/
[[licenses.clarify]]
name = "nihav_core"
expression = "MIT"
license-files = []

[[licenses.clarify]]
name = "nihav_duck"
expression = "MIT"
license-files = []

[[licenses.clarify]]
name = "nihav_codec_support"
expression = "MIT"
license-files = []

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"

deny = [
    # We are manually pinning `tracing-tracy` to match the version used by
    # `profiling`, but this can get stale easily.
    { name = "tracy-client", deny-multiple-versions = true },
    # Having multiple versions of this can silently cause images (such as
    # the logo in the about dialog) in egui to not appear.
    { name = "image", deny-multiple-versions = true },
]

[sources]
# Lint level for what to happen when a crate from a crate registry that is not
# in the allow list is encountered
unknown-registry = "deny"
# Lint level for what to happen when a crate from a git repository that is not
# in the allow list is encountered
unknown-git = "deny"

[sources.allow-org]
#  github.com organizations to allow git sources for
github = [
    "ruffle-rs",
]

[advisories]
version = 2
