[package]
name = "ruffle_scanner"
version = "0.1.0"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
clap = "3.0.0-beta.4"
ruffle_core = { path = "../core" }
env_logger = "0.9.0"
log = "0.4"
walkdir = "2.3.2"
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
indicatif = "0.16"
path-slash = "0.1.4"
swf = { path = "../swf" }
rayon = "1.5.1"
crossbeam-channel = "0.5"
sha2 = "0.9.8"