[package]
name = "ruffle_render_wgpu"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>"]
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
wgpu = { workspace = true, features = ["naga-ir"] }
tracing = { workspace = true }
ruffle_render = { path = "..", features = ["tessellator", "wgpu"] }
bytemuck = { version = "1.15.0", features = ["derive"] }
raw-window-handle = "0.6.0"
clap = { version = "4.5.4", features = ["derive"], optional = true }
enum-map = "2.7.3"
fnv = "1.0.7"
swf = { path = "../../swf" }
image = { version = "0.25.0", default-features = false }
naga_oil = { workspace = true }
naga-agal = { path = "../naga-agal" }
naga-pixelbender = { path = "../naga-pixelbender" }
downcast-rs = "1.2.0"
profiling = { version = "1.0", default-features = false, optional = true }
lru = "0.12.3"
naga = { workspace = true }
indexmap = "2.2.6"

# desktop
[target.'cfg(not(target_family = "wasm"))'.dependencies.futures]
version = "0.3.30"

# wasm
[target.'cfg(target_family = "wasm")'.dependencies.web-sys]
version = "0.3.69"
features = ["HtmlCanvasElement"]

[features]
render_debug_labels = []
render_trace = ["wgpu/trace"]
webgl = ["wgpu/webgl"]
profile-with-tracy = ["profiling", "profiling/profile-with-tracy"]
