[package]
name = "ruffle_render_wgpu"
version = "0.1.0"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
wgpu = "0.9.0"
image = "0.23.14"
log = "0.4"
ruffle_core = { path = "../../core" }
ruffle_render_common_tess = { path = "../common_tess" }
futures = "0.3.17"
bytemuck = { version = "1.7.0", features = ["derive"] }
raw-window-handle = "0.3.3"
clap = { version = "3.0.0-beta.4", optional = true }
enum-map = "1.1.1"

[features]
render_debug_labels = []
render_trace = ["wgpu/trace"]
