[package]
name = "ruffle_render_wgpu"
version = "0.1.0"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
wgpu = "0.5"
wgpu-native = "0.5"
image = "0.23.7"
jpeg-decoder = "0.1.20"
log = "0.4"
lyon = "0.15.9"
ruffle_core = { path = "../../core" }
futures = "0.3.5"
bytemuck = "1.3.1"
raw-window-handle = "0.3.3"

[features]
render_debug_labels = []