[package]
name = "ruffle_render_wgpu"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>"]
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "e3ebb03d0f14716bc0527f8076c9efae1fbad4c6", features = ["naga"] }
tracing = "0.1.37"
ruffle_render = { path = "..", features = ["tessellator"] }
bytemuck = { version = "1.12.3", features = ["derive"] }
raw-window-handle = "0.5"
clap = { version = "4.0.32", features = ["derive"], optional = true }
enum-map = "2.4.2"
fnv = "1.0.7"
swf = { path = "../../swf" }
image = { version = "0.24.5", default-features = false }
naga_oil = { git = "https://github.com/Dinnerbone/naga_oil", rev = "c073f6fdf0560a74480140abc50295f9e0d9aa57" }
ouroboros = "0.15.5"
typed-arena = "2.0.2"
once_cell = "1.17.0"
gc-arena = { workspace = true }
naga-agal = { path = "../naga-agal" }
downcast-rs = "1.2.0"
profiling = { version = "1.0", default-features = false, optional = true }

# desktop
[target.'cfg(not(target_family = "wasm"))'.dependencies.futures]
version = "0.3.25"

# wasm
[target.'cfg(target_family = "wasm")'.dependencies.web-sys]
version = "0.3.60"
features = ["HtmlCanvasElement"]

[features]
render_debug_labels = []
render_trace = ["wgpu/trace"]
webgl = ["wgpu/webgl"]
profile-with-tracy = ["profiling", "profiling/profile-with-tracy"]
