[package]
name = "ruffle_render_wgpu"
version = "0.1.0"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>"]
edition.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]
wgpu = { version = "0.14.0", features = ["naga"] }
# Pin `wgpu-hal` and `wgpu-types` to include https://github.com/gfx-rs/wgpu/pull/3165.
# TODO: Remove when upgrading `wgpu`.
wgpu-hal = "0.14.1"
wgpu-types = "0.14.1"
log = "0.4"
ruffle_render = { path = "..", features = ["tessellator"] }
bytemuck = { version = "1.12.3", features = ["derive"] }
raw-window-handle = "0.5"
clap = { version = "4.0.27", features = ["derive"], optional = true }
enum-map = "2.4.1"
fnv = "1.0.7"
swf = { path = "../../swf" }
image = { version = "0.24.5", default-features = false }
ouroboros = "0.15.5"
typed-arena = "2.0.1"
once_cell = "1.16.0"
gc-arena = { git = "https://github.com/ruffle-rs/gc-arena" }
naga-agal = { path = "../naga-agal" }
downcast-rs = "1.2.0"

# desktop
[target.'cfg(not(target_family = "wasm"))'.dependencies.futures]
version = "0.3.25"

# wasm
[target.'cfg(target_family = "wasm")'.dependencies.web-sys]
version = "0.3.60"
features = ["HtmlCanvasElement"]

[features]
render_debug_labels = []
render_trace = ["wgpu/trace"]
webgl = ["wgpu/webgl"]
