[package]
name = "ruffle_render_wgpu"
version = "0.1.0"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
wgpu = "0.13.0"
log = "0.4"
ruffle_render = { path = "..", features = ["tessellator"] }
bytemuck = { version = "1.12.1", features = ["derive"] }
raw-window-handle = "0.4"
clap = { version = "3.2.18", features = ["derive"], optional = true }
enum-map = "2.4.1"
fnv = "1.0.7"
swf = { path = "../../swf" }

# desktop
[target.'cfg(not(target_family = "wasm"))'.dependencies.futures]
version = "0.3.24"

[target.'cfg(not(target_family = "wasm"))'.dependencies.image]
version = "0.24.2"
default-features = false

# wasm
[target.'cfg(target_family = "wasm")'.dependencies.web-sys]
version = "0.3.58"
features = ["HtmlCanvasElement"]

[features]
render_debug_labels = []
render_trace = ["wgpu/trace"]
webgl = ["wgpu/webgl"]
