[package]
name = "ruffle_video_external"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
ruffle_render = { path = "../../render" }
ruffle_video = { path = ".." }
swf = { path = "../../swf" }
slotmap = { workspace = true }
tracing = { workspace = true }
ruffle_video_software = { path = "../software" }
thiserror = { workspace = true }

# Needed for OpenH264:
libloading = { version = "0.8.6", optional = true }
reqwest = { version = "0.12.9", default-features = false, features = ["blocking"], optional = true }
hex = { version = "0.4.3", optional = true }
bzip2 = { version = "0.5.0", features = ["static"], optional = true }
tempfile = { version = "3.14.0", optional = true }
sha2 = { version = "0.10.8", optional = true }

[features]
openh264 = ["libloading", "reqwest", "hex", "bzip2", "tempfile", "sha2"]
