[package]
name = "ruffle_web_safari"
description = "Native binary for the Safari Web Extension"
authors.workspace = true
edition = "2024"
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
publish = false # This crate is useless unless packaged into an appex bundle

[lints]
workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.3"
