[package]
name = "ruffle_core"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
byteorder = "1.4"
bitstream-io = "1.2.0"
flate2 = "1.0.20"
fnv = "1.0.7"
gc-arena = { git = "https://github.com/ruffle-rs/gc-arena" }
gc-arena-derive = { git = "https://github.com/ruffle-rs/gc-arena" }
generational-arena = "0.2.8"
gif = "0.11.2"
indexmap = "1.6.2"
log = "0.4"
minimp3 = { version = "0.5.1", optional = true }
png = { version = "0.17.0" }
ruffle_macros = { path = "macros" }
swf = { path = "../swf" }
bitflags = "1.3.2"
smallvec = "1.6.1"
num-traits = "0.2"
num-derive = "0.3"
quick-xml = { git = "https://github.com/ruffle-rs/quick-xml", rev = "8496365ec1412eb5ba5de350937b6bce352fa0ba" }
downcast-rs = "1.2.0"
url = "2.2.2"
weak-table = "0.3.0"
percent-encoding = "2.1.0"
thiserror = "1.0"
chrono = "0.4"
instant = "0.1"
encoding_rs = "0.8.28"
rand = { version = "0.8.4", features = ["std", "small_rng"], default-features = false }
serde = { version = "1.0.130", features = ["derive"], optional = true }
nellymoser-rs = { git = "https://github.com/ruffle-rs/nellymoser" }
h263-rs = { git = "https://github.com/ruffle-rs/h263-rs", rev = "ce3d3c798190be1c78c47099e76d095756a195ac", optional = true }
h263-rs-yuv = { git = "https://github.com/ruffle-rs/h263-rs", rev = "ce3d3c798190be1c78c47099e76d095756a195ac", optional = true }
regress = "0.4"
flash-lso = { git = "https://github.com/ruffle-rs/rust-flash-lso", rev = "19fecd07b9888c4bdaa66771c468095783b52bed" }
json = "0.12.4"
lzma-rs = {version = "0.2.0", optional = true }

[dependencies.jpeg-decoder]
version = "0.1.22"
default-features = false # can't use rayon on web

[dev-dependencies]
approx = "0.5.0"
pretty_assertions = "0.7.2"
env_logger = "0.9.0"

[features]
default = ["minimp3", "serde"]
h263 = ["h263-rs", "h263-rs-yuv"]
lzma = ["lzma-rs", "swf/lzma"]
wasm-bindgen = [ "instant/wasm-bindgen" ]
avm_debug = []
