[package]
name = "ruffle_core"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"

[dependencies]
bitstream-io = "0.8.2"
gc = "0.3.3"
gc_derive = "0.3.2"
generational-arena = "0.2.2"
log = "0.4"
rand = "0.6.5"
swf = { git = "https://github.com/Herschel/swf-rs", rev = "afbf8fd" }
