[package]
name = "ruffle_core"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"

[dependencies]
bitstream-io = "0.8.5"
fnv = "1.0.3"
gc-arena = "0.2.0"
gc-arena-derive = "0.2.0"
generational-arena = "0.2.7"
indexmap = "1.3.2"
libflate = "0.1.26"
log = "0.4"
minimp3 = { version = "0.3.5", optional = true }
puremp3 = { version = "0.1", optional = true }
ruffle_macros = { path = "macros" }
swf = { path = "../swf" }
enumset = "1.0.0"
smallvec = "1.3.0"
num_enum = "0.4.3"
quick-xml = "0.18.1"
downcast-rs = "1.1.1"
url = "2.1.0"
weak-table = "0.2.3"

[dependencies.jpeg-decoder]
version = "0.1.18"
default-features = false # can't use rayon on web

[dependencies.rand]
version = "0.7.3"
features = ["small_rng"]

[dev-dependencies]
approx = "0.3.2"
pretty_assertions = "0.6.1"

[features]
default = ["minimp3"]
lzma = ["swf/lzma"]
avm_debug = []
