[package]
name = "ruffle_core"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
bitstream-io = "0.9.0"
flate2 = "1.0.19"
fnv = "1.0.7"
gc-arena = "0.2.0"
gc-arena-derive = "0.2.0"
generational-arena = "0.2.8"
gif = "0.11.1"
indexmap = "1.6.1"
log = "0.4"
minimp3 = { version = "0.5.0", optional = true }
png = { version = "0.16.8" }
puremp3 = { version = "0.1", optional = true }
ruffle_macros = { path = "macros" }
swf = { path = "../swf" }
enumset = "1.0.1"
smallvec = "1.5.1"
num_enum = "0.5.1"
quick-xml = "0.20.0"
downcast-rs = "1.2.0"
url = "2.2.0"
weak-table = "0.3.0"
percent-encoding = "2.1.0"
thiserror = "1.0"
json = "0.12.4"
chrono = "0.4"
num-traits = "0.2"
instant = "0.1"
encoding_rs = "0.8.26"

[dependencies.jpeg-decoder]
version = "0.1.20"
default-features = false # can't use rayon on web

[dependencies.rand]
version = "0.8.0"
features = ["small_rng"]

[dev-dependencies]
approx = "0.4.0"
pretty_assertions = "0.6.1"

[features]
default = ["minimp3"]
lzma = ["swf/lzma"]
wasm-bindgen = [ "instant/wasm-bindgen" ]
avm_debug = []
