[package]
name = "ruffle_render_webgl"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"

[dependencies]
fnv = "1.0.3"
js-sys = "0.3.25"
log = "0.4" 
percent-encoding = "2.1.0"
png = "0.16.3"
ruffle_render_common_tess = { path = "../common_tess" }
ruffle_web_common = { path = "../../web/common" }
wasm-bindgen = "0.2.57"

[dependencies.jpeg-decoder]
version = "0.1.18"
default-features = false

[dependencies.ruffle_core]
path = "../../core"
default-features = false

[dependencies.web-sys]
version = "0.3.34"
features = ["HtmlCanvasElement", "HtmlElement", "Node", "WebGlBuffer", "WebGlProgram", "WebGlRenderingContext", 
            "WebGl2RenderingContext", "WebGlShader", "WebGlTexture", "WebGlUniformLocation"]
