[package]
name = "ruffle_render_webgl"
version = "0.1.0"
authors = ["Ruffle LLC <ruffle@ruffle.rs>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
js-sys = "0.3.59"
log = "0.4"
ruffle_render_common_tess = { path = "../common_tess" }
ruffle_web_common = { path = "../../web/common" }
ruffle_render = { path = ".." }
wasm-bindgen = "=0.2.82"
bytemuck = { version = "1.10.0", features = ["derive"] }
fnv = "1.0.7"
swf = { path = "../../swf" }

[dependencies.web-sys]
version = "0.3.58"
features = [
    "HtmlCanvasElement", "OesVertexArrayObject", "WebGl2RenderingContext", "WebGlBuffer", "WebglDebugRendererInfo",
    "WebGlFramebuffer", "WebGlProgram", "WebGlRenderbuffer", "WebGlRenderingContext", "WebGlShader", "WebGlTexture",
    "WebGlUniformLocation", "WebGlVertexArrayObject",
]
