[package]
name = "ruffle_render_webgl"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
js-sys = "0.3.69"
log = "0.4"
ruffle_web_common = { path = "../../web/common" }
ruffle_render = { path = "..", features = ["tessellator", "web"] }
wasm-bindgen = "=0.2.92"
bytemuck = { version = "1.15.0", features = ["derive"] }
swf = { path = "../../swf" }
thiserror = "1.0"
downcast-rs = "1.2.0"

[dependencies.web-sys]
version = "0.3.69"
features = [
    "HtmlCanvasElement", "OesVertexArrayObject", "WebGl2RenderingContext", "WebGlBuffer", "WebglDebugRendererInfo",
    "WebGlFramebuffer", "WebGlProgram", "WebGlRenderbuffer", "WebGlRenderingContext", "WebGlShader", "WebGlTexture",
    "WebGlUniformLocation", "WebGlVertexArrayObject",
]
