[package]
name = "ruffle_render"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
ruffle_wstr = { path = "../wstr" }
swf = { path = "../swf"}
tracing = "0.1.37"
gif = "0.12.0"
png = { version = "0.17.8" }
flate2 = "1.0.26"
smallvec = { version = "1.10.0", features = ["union"] }
downcast-rs = "1.2.0"
lyon = { version = "1.0.1", optional = true }
thiserror = "1.0"
wasm-bindgen = { version = "=0.2.86", optional = true }
gc-arena = { workspace = true }
enum-map = "2.5.0"
serde = { version = "1.0.164", features = ["derive"] }
clap = { version = "4.3.3", features = ["derive"], optional = true }
h263-rs-yuv = { git = "https://github.com/ruffle-rs/h263-rs", rev = "d5d78eb251c1ce1f1da57c63db14f0fdc77a4b36"}
lru = "0.10.0"

[dependencies.jpeg-decoder]
version = "0.3.0"
default-features = false # can't use rayon on web

[dev-dependencies]
approx = "0.5.1"

[features]
default = []
tessellator = ["lyon"]
web = ["wasm-bindgen"]
