[package]
name = "ruffle_render"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
ruffle_wstr = { path = "../wstr" }
swf = { path = "../swf"}
tracing = "0.1.37"
gif = "0.12.0"
png = { version = "0.17.7" }
flate2 = "1.0.25"
smallvec = { version = "1.10.0", features = ["union"] }
downcast-rs = "1.2.0"
lyon = { version = "1.0.1", optional = true }
thiserror = "1.0"
wasm-bindgen = { version = "=0.2.84", optional = true }
gc-arena = { workspace = true }
enum-map = "2.4.2"
serde = { version = "1.0.152", features = ["derive"] }
clap = { version = "4.1.6", features = ["derive"], optional = true }

[dependencies.jpeg-decoder]
version = "0.3.0"
default-features = false # can't use rayon on web

[dev-dependencies]
approx = "0.5.1"

[features]
default = []
tessellator = ["lyon"]
web = ["wasm-bindgen"]
