[package]
name = "ruffle_render"
version = "0.1.0"
authors = ["Ruffle LLC <ruffle@ruffle.rs>"]
edition.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]
swf = { path = "../swf"}
log = "0.4"
gif = "0.12.0"
png = { version = "0.17.7" }
flate2 = "1.0.24"
smallvec = { version = "1.10.0", features = ["union"] }
downcast-rs = "1.2.0"
lyon = { version = "1.0.1", optional = true }
thiserror = "1.0"
wasm-bindgen = { version = "=0.2.83", optional = true }
gc-arena = { git = "https://github.com/ruffle-rs/gc-arena" }

[dependencies.jpeg-decoder]
version = "0.3.0"
default-features = false # can't use rayon on web

[dev-dependencies]
approx = "0.5.1"

[features]
default = []
tessellator = ["lyon"]
web = ["wasm-bindgen"]
