[package]
name = "ruffle_web_common"
version = "0.1.0"
authors = ["Ruffle LLC <ruffle@ruffle.rs>"]
edition.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]
js-sys = "0.3.60"
tracing = "0.1.37"
wasm-bindgen = "=0.2.84"

[dependencies.web-sys]
version = "0.3.60"
features = ["Window"]
