[package]
name = "ruffle_web_common"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
js-sys = "0.3.53"
log = "0.4"
wasm-bindgen = "=0.2.76"

[dependencies.web-sys]
version = "0.3.50"
features = ["Window"]
