[package]
name = "ruffle_macros"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.15"

[dependencies.syn]
version = "1.0.87"
features = ["full"]
