[package]
name = "ruffle_macros"
version = "0.1.0"
authors = ["Ruffle LLC <ruffle@ruffle.rs>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.19"
syn = { version = "1.0.98", features = ["full"] }
