[package]
name = "ruffle_gc_arena"
version = "0.0.0"
description = "Temporary, internal gc-arena facade for Ruffle"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gc-arena = { git = "https://github.com/kyren/gc-arena", rev = "efd89fc683c6bb456af3e226c33763cb822645e9", features = ["hashbrown"] }
