[package]
name = "naga-agal"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
bitflags = "1.3.2"
naga = { version = "0.10.0" }
num-derive = "0.3.3"
num-traits = "0.2.15"

[dev-dependencies]
insta = "1.23.0"
naga = { version = "0.10.0", features = ["wgsl-out", "validate"] }
