[package]
name = "swf"
version = "0.1.2"
edition = "2021"
authors = ["Mike Welsh"]
repository = "https://github.com/ruffle-rs/ruffle"
homepage = "https://github.com/ruffle-rs/ruffle"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Read and write the Adobe Flash SWF file format."

[dependencies]
bitflags = "1.3.2"
bitstream-io = "1.3.0"
byteorder = "1.4"
encoding_rs = "0.8.30"
num-derive = "0.3"
num-traits = "0.2"
libflate = {version = "1.2", optional = true}
log = "0.4"
flate2 = {version = "1.0", optional = true}
lzma-rs = {version = "0.2.0", optional = true }

[features]
default = ["flate2", "lzma"]
lzma = ["lzma-rs"]
