[package]
name = "swf"
version = "0.2.0"
edition.workspace = true
authors = ["Ruffle LLC <ruffle@ruffle.rs>"]
repository = "https://github.com/ruffle-rs/ruffle"
homepage = "https://github.com/ruffle-rs/ruffle"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Read and write the Adobe Flash SWF file format."

[dependencies]
bitflags = "1.3.2"
bitstream-io = "1.6.0"
byteorder = "1.4"
encoding_rs = "0.8.31"
num-derive = "0.3"
num-traits = "0.2"
libflate = {version = "1.2", optional = true}
log = "0.4"
flate2 = {version = "1.0", optional = true}
lzma-rs = {version = "0.2.0", optional = true }
enum-map = "2.4.1"
simple_asn1 = "0.6.2"

[features]
default = ["flate2", "lzma"]
lzma = ["lzma-rs"]
