[package]
name = "swf"
version = "0.2.0"
description = "Read and write the Adobe Flash SWF file format."
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bitflags = "2.4.1"
bitstream-io = "2.2.0"
byteorder = "1.5"
encoding_rs = "0.8.33"
num-derive = "0.4"
num-traits = "0.2"
libflate = {version = "2.0", optional = true}
log = "0.4"
flate2 = {version = "1.0", optional = true}
lzma-rs = {version = "0.3.0", optional = true }
enum-map = "2.7.3"
simple_asn1 = "0.6.2"

[features]
default = ["flate2", "lzma"]
lzma = ["lzma-rs"]
