[package]
name = "swf"
version = "0.1.2"
edition = "2018"
authors = ["Mike Welsh"]
repository = "https://github.com/ruffle-rs/ruffle"
homepage = "https://github.com/ruffle-rs/ruffle"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Read and write the Adobe Flash SWF file format."

[dependencies]
byteorder = "1.0"
num-derive = "0.3"
num-traits = "0.2"
libflate = {version = "0.1", optional = true}
log = "0.4"
flate2 = {version = "1.0", optional = true}
xz2 = {version = "0.1.6", optional = true}

[features]
default = ["libflate"]
lzma = ["xz2"]