[package]
name = "build_playerglobal"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.79"
quote = "1.0.35"
swf = { path = "../../swf" }
clap = {version = "4.5.3", features = ["derive"]}
serde = {version = "1.0.197", features = ["derive"]}
serde-xml-rs = "0.6.0"
colored = "2.1.0"
regex = "1.10.3"
walkdir = "2.5.0"
