[package]
name = "build_playerglobal"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.86"
quote = "1.0.37"
swf = { path = "../../swf" }
clap = { workspace = true }
regex = "1.10.6"
walkdir = { workspace = true }
