[package]
name = "build_playerglobal"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.79"
quote = "1.0.35"
swf = { path = "../../swf" }
clap = {version = "4.5.4", features = ["derive"]}
regex = "1.10.4"
walkdir = "2.5.0"
