[package]
name = "build_playerglobal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swf = { path = "../../swf" }
walkdir = "2.3.2"
