[package]
name = "build_playerglobal"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.69"
quote = "1.0.33"
swf = { path = "../../swf" }
clap = {version = "4.4.6", features = ["derive"]}
serde = {version = "1.0.189", features = ["derive"]}
serde-xml-rs = "0.6.0"
colored = "2.0.4"
regex = "1.10.2"
walkdir = "2.4.0"
