[package]
name = "ruffle_render_common_tess"
version = "0.1.0"
authors = ["Ruffle LLC <ruffle@ruffle.rs>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
log = "0.4"
lyon = "1.0.0"
ruffle_render = { path = ".." }
swf = { path = "../../swf" }
