name: Upload source texts to Crowdin

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  crowdin:
    runs-on: ubuntu-24.04

    if: github.repository == 'ruffle-rs/ruffle'

    strategy:
      max-parallel: 1 # Should be 1 to avoid parallel builds
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y itstool gettext appstream

      - name: Generate desktop & metainfo sources
        working-directory: desktop/packages/linux
        run: |
          make update

      - name: Upload intermediate files
        uses: actions/upload-artifact@v6
        with:
          path: desktop/packages/linux/locale

      - name: Crowdin push
        uses: crowdin/github-action@v2
        with:
          config: 'crowdin.yml'
          upload_sources: true
          upload_translations: false
          download_translations: false
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
