[package]
name = "ruffle_desktop"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }
cpal = "0.15.2"
egui = { workspace = true }
egui_extras = { version = "0.24.2", features = ["image"] }
egui-wgpu = { version = "0.24.1", features = ["winit"] }
image = { version = "0.24", features = ["png"] }
egui-winit = "0.24.1"
fontdb = "0.16"
ruffle_core = { path = "../core", features = ["audio", "clap", "mp3", "nellymoser", "default_compatibility_rules", "egui", "default_font"] }
ruffle_render = { path = "../render", features = ["clap"] }
ruffle_render_wgpu = { path = "../render/wgpu", features = ["clap"] }
ruffle_video_software = { path = "../video/software", optional = true }
tracing = { workspace = true}
tracing-subscriber = { workspace = true }
generational-arena = "0.2.9"
winit = "0.28.7"
webbrowser = "0.8.12"
url = "2.5.0"
arboard = { version = "3.3.0", features = ["wayland-data-control"] }
dirs = "5.0"
isahc = { version = "1.7.2", features = ["cookies"] }
rfd = "0.12.1"
anyhow = "1.0"
bytemuck = "1.14.0"
os_info = { version = "3", default-features = false }
unic-langid = "0.9.4"
sys-locale = "0.3.1"
wgpu = { workspace = true }
futures = "0.3.30"
chrono = { version = "0.4", default-features = false, features = [] }
fluent-templates = "0.8.0"
futures-lite = "2.1.0"
async-io = "2.2.2"
async-net = "2.0.0"
async-channel = "2.1.1"

# Deliberately held back to match tracy client used by profiling crate
tracing-tracy = { version = "=0.10.4", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[build-dependencies]
embed-resource = "2"
vergen = { version = "8.2.6", features = ["build", "git", "gitcl", "cargo"] }

[features]
default = ["software_video"]
jpegxr = ["ruffle_core/jpegxr"]

# core features
avm_debug = ["ruffle_core/avm_debug"]
lzma = ["ruffle_core/lzma"]
software_video = ["ruffle_video_software"]
tracy = ["tracing-tracy", "ruffle_render_wgpu/profile-with-tracy"]

# wgpu features
render_debug_labels = ["ruffle_render_wgpu/render_debug_labels"]
render_trace = ["ruffle_render_wgpu/render_trace"]

# sandboxing
sandbox = []
