[package]
name = "ruffle_desktop"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"

[dependencies]
ruffle_core = { path = "../core" }
glium = "0.24"
glutin = "0.20"
env_logger = "0.6.1"
generational-arena = "0.2.2"
image = "0.21.1"
inflate = "0.4.5"
jpeg-decoder = "0.1.15"
log = "0.4"
lyon = "0.13.3"
minimp3 = { git = "https://github.com/germangb/minimp3-rs" }
structopt = "0.2.15"
winit = "0.19.1"

[dependencies.rodio]
version = "0.8.1"
features = ["mp3"]