[package]
name = "ruffle_desktop"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"
default-run = "ruffle_desktop"
license = "MIT OR Apache-2.0"

[dependencies]
cpal = "0.12.0"
ruffle_core = { path = "../core" }
ruffle_render_wgpu = { path = "../render/wgpu" }
env_logger = "0.7.1"
generational-arena = "0.2.8"
image = "0.23.7"
jpeg-decoder = "0.1.20"
log = "0.4"
lyon = "0.15.9"
sample = "0.11.0"
structopt = "0.3.15"
winit = "0.22"
webbrowser = "0.5.5"
url = "2.1.1"
clipboard = "0.5.0"
dirs = "3.0"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[target.'cfg(windows)'.build-dependencies]
embed-resource = "1"

[features]
avm_debug = ["ruffle_core/avm_debug"]
render_debug_labels = ["ruffle_render_wgpu/render_debug_labels"]
lzma = ["ruffle_core/lzma"]
