[package]
name = "ruffle_desktop"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"
default-run = "ruffle_desktop"

[dependencies]
cpal = "0.11.0"
ruffle_core = { path = "../core" }
ruffle_render_wgpu = { path = "../render/wgpu" }
env_logger = "0.7.1"
generational-arena = "0.2.7"
image = "0.23.4"
jpeg-decoder = "0.1.19"
log = "0.4"
lyon = "0.15.8"
sample = "0.10.0"
structopt = "0.3.14"
winit = "0.22"
webbrowser = "0.5.2"
url = "2.1.1"

[features]
avm_debug = ["ruffle_core/avm_debug"]
lzma = ["ruffle_core/lzma"]
