[package]
name = "ruffle_desktop"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
cpal = "0.14.2"
ruffle_core = { path = "../core", features = ["audio", "mp3", "nellymoser"] }
ruffle_render_wgpu = { path = "../render/wgpu", features = ["clap"] }
ruffle_video_software = { path = "../video/software", optional = true }
env_logger = { version = "0.10", default-features = false, features = ["humantime"] }
generational-arena = "0.2.8"
log = "0.4"
winit = "0.27.5"
webbrowser = "0.8.4"
url = "2.3.1"
arboard = "3.2.0"
dirs = "4.0"
isahc = "1.7.2"
rfd = "0.10.0"
anyhow = "1.0"
bytemuck = "1.12.3"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[build-dependencies]
embed-resource = "1"

[features]
default = ["software_video"]

# core features
avm_debug = ["ruffle_core/avm_debug"]
lzma = ["ruffle_core/lzma"]
software_video = ["ruffle_video_software"]

# wgpu features
render_debug_labels = ["ruffle_render_wgpu/render_debug_labels"]
render_trace = ["ruffle_render_wgpu/render_trace"]

# sandboxing
sandbox = []
