[package]
name = "ruffle_desktop"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"
default-run = "ruffle_desktop"
license = "MIT OR Apache-2.0"

[dependencies]
clap = "3.0.0-beta.2"
cpal = "0.13.1"
ruffle_core = { path = "../core" }
ruffle_render_wgpu = { path = "../render/wgpu", features = ["clap"] }
env_logger = "0.8.2"
generational-arena = "0.2.8"
image = "0.23.12"
jpeg-decoder = "0.1.20"
log = "0.4"
lyon = "0.16.2"
dasp = {version = "0.11.0", git = "https://github.com/RustAudio/dasp", rev = "f05a703", features = ["interpolate", "interpolate-linear", "signal"]}
winit = "0.24.0"
webbrowser = "0.5.5"
url = "2.2.0"
clipboard = "0.5.0"
dirs = "3.0"
isahc = "1.0.1"
tinyfiledialogs = {git ="https://github.com/jdm/tinyfiledialogs-rs", rev="1a235d1"}

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[target.'cfg(windows)'.build-dependencies]
embed-resource = "1"

[features]
avm_debug = ["ruffle_core/avm_debug"]
render_debug_labels = ["ruffle_render_wgpu/render_debug_labels"]
render_trace = ["ruffle_render_wgpu/render_trace"]
lzma = ["ruffle_core/lzma"]
